### ISSUE TITLE
Article sur Muzeodrome

### ISSUE THREAD

**Issue by gchetanian** [ouvroir/museadon#25]

**Comment by gchetanian** [comment]
Muzeodrome une infolettre qui lettre qui répertorie l'inventivité des musées

Spécialiste de la muséologie numérique, Omer Presquer documente depuis en novembre 2019, Muzeodrome une infolettre hebdomadaire consacrée à l'inventivité des musées et des expositions. Il s'agit d'un travail de veille qui met en avant la présence des musées sur les réseaux sociaux, les solutions que ceux-ci font de l'usage du numérique, mais aussi de l'observation sensible que l'auteur porte sur le sujet. Brève, ponctuée d'émojis bien choisis qui en égayent la lecture, cette lettre paraissant chaque lundi tombe à point pour commencer la semaine dans de bonnes conditions. Bien qu'il soit d'abord recommandé de s'abonner il est aussi possible de consulter les anciennes lettres sur le site dédié.

**Comment by emchateau** [comment]
# Muzeodrome, une infolettre qui répertorie l’inventivité des musées

Spécialiste de la muséologie numérique, Omer Presquer édite et publie depuis novembre 2019, [Muzeodrome](https://muzeodrome.substack.com/) une infolettre hebdomadaire consacrée à l'inventivité des musées et des expositions. Il s’agit d’un travail de veille qui met en avant la présence des musées sur les réseaux sociaux, les solutions numériques que ceux-ci mettent en œuvre, mais aussi les observations sensibles de l’auteur porte sur le secteur. Brève, ponctuée d’émojis bien choisis qui en égayent la lecture, cette lettre qui paraît chaque lundi tombe à point pour commencer la semaine dans de bonnes conditions. Même s’il est recommandé de s’abonner, il est aussi possible de consulter les anciennes lettres sur la page web dédiée.

**Comment by emchateau** [comment]
@gchetanian idem, si vous voulez je peux préparer l’article

**Comment by emchateau** [comment]
Proposition intégrée
