### ISSUE TITLE
Compte-rendu museocovid

### ISSUE THREAD

**Issue by emchateau** [ouvroir/museadon#27]
http://museocovid.org/

**Comment by gchetanian** [comment]
# Compte-rendu museocovid
Museocovid est une initiative française initiée par plusieurs musées pendant le confinement afin de pouvoir échanger collectivement sur la situation de leurs établissements. La première réunion s'est tenue le 19 mai 2020 et a réuni environ 300 participants. Devant une telle affluence, il a été décidé de créer plusieurs groupes afin que la parole circule mieux.
De par la volonté des animateurs de travailler avec des plateformes non propriétaires les conférences ont eu lieues sur la plateforme de visioconférence **_[Jitsi](https://fr.wikipedia.org/wiki/Jitsi)_** et se sont poursuivi sur la plateforme collaborative **_[Klaxoon](https://fr.wikipedia.org/wiki/Klaxoon)_**

**Comment by emchateau** [comment]
# Compte-rendu museocovid
[Logo Museocovid](assets/images/muscov_s.png)

[Museocovid](http://www.museocovid.org/index.php?) est une initiative française initiée par plusieurs musées pendant le confinement afin de pouvoir échanger collectivement sur la situation de leurs établissements. Pour l'occasion un site internet a été créé qui a bénéficié du soutien des Musées de Bretagne, de la Fédération des Écomusées et des Musées de Sociétés (FEMS), de la fabrique de patrimoine en Normandie, du réseau des musées de Normandie, de l’Université de Rennes 2 et de Muséomix.

La première réunion intitulée _Réinvestir l'espace du musée_ s’est tenue le 19 mai 2020 et a rassemblé environ 300 participants. Devant une telle affluence, il a été décidé de créer plusieurs groupes afin que la parole circule mieux. Les organisateurs ont fait le choix volontariste de travailler avec des plateformes non propriétaires. Ainsi, les conférences se sont déroulées sur la plateforme de visioconférence **_[Jitsi](https://fr.wikipedia.org/wiki/Jitsi)_** et se sont poursuivies sur la plateforme collaborative **_[Klaxoon](https://fr.wikipedia.org/wiki/Klaxoon)_**. 

Une seconde réunion est programmée le le 25 juin à 14h (heure française) les inscriptions seront ouvertes à partir du 16 juin.

**Comment by emchateau** [comment]
Si les corrections vous conviennent, j’intègre dans un article ou vous le faites @gchetanian ?

**Comment by emchateau** [comment]
@gchetanian Mes excuses, il était dans le pull request. J’intègre.
