### ISSUE TITLE
Question concernant l'article de blog à écrire 

### ISSUE THREAD

**Issue by CamilleRV** [ouvroir/museadon#48]
Bonjour! 

Ma question concerne l'article de blog à écrire sur la plateforme. Pourrait-il aussi s'agir d'un résumé d'article intéressant concernant un enjeu ou un débat entourant le numérique et les musées? 

Merci d'avance! 

Camille.

**Comment by Alissia-CptBath** [comment]
Bonjour @CamilleRV 

ton article présente-il une initiative particulière « non physique » ?

**Comment by Alissia-CptBath** [comment]
@emchateau l'article de blog peut-il concerner une technologie qui a été détourner de ces fonctions premières ? c'est à dire qu'au lieu d'utiliser un appareil qui consomme beaucoup d'énergie, il a été remplacé par autre chose dont la fonction initiale n'a rien à voir. Merci

**Comment by CamilleRV** [comment]
@Alissia-CptBath @emchateau Oui, il s'agissait d'un article sur les enjeux entourant la mise en ligne de patrimoine documentaire ou de fonds patrimoniaux sur Wikipédia par des institutions culturelles. Mais j'ai pensé à autre chose!

Je me demandais simplement si l'article devait absolument traiter d'une initiative concrète d'un musée ou d'un autre organisme.

**Comment by Alissia-CptBath** [comment]
@CamilleRV Ton article doit être intéressant mais si je comprends bien, il semble plus s'occuper de la documentation et donc du catalogage et du traitement des données avec les enjeux autour et je pense que ce n'est pas le sujet demandé ici. Mais si tu as trouvé autre chose tant mieux ! 

Pour le reste, il faudrait voir avec Emmanuel directement.

**Comment by emchateau** [comment]
@Alissia-CptBath le détournement d’une technologie est une stratégie courante dans le domaine du hacking. C’est une démarche particulièrement intéressante pour ce qui nous concerne. L‘initiative n’a pas forcément besoin de porter directement sur la muséologie, elle peut venir d’un domaine connexe ou tout aussi bien concerner une initiative que vous trouvez inspirante par sa démarche. Dans ce cas, à vous de la ramener dans le champ par votre manière de l’aborder. @CamilleRV Vous pouvez travailler à partir d’un article, mais l’idée est vraiment si possible d’évoquer des réalisations concrètes. Le cas des fonds patrimoniaux et de Wikipédia est intéressant car il s’agit de démarche relativement faciles à mettre en œuvre du point de vue technologique, mais elles nécessitent un important ingénierie social.

**Comment by Alissia-CptBath** [comment]
@ouvroir/museadon Hello tout le monde, 
@JulienLehoux je me souviens que tu parlais de podcast, j'ai trouvée un podcast qui pourrait t'intéresser et t'inspirer peut-être concernant le projet final ou l'article de blog:    []([](https://www.sortiraparis.com/arts-culture/exposition/articles/243779-le-musee-du-louvre-lance-ses-enquetes-du-louvre-un-podcast-qui-mele-art-et-crime#))

**Comment by veroforget** [comment]
Bonjour! @emchateau je vous reviens pour l'article sur le thème de collection virtuelle et interactive! Comme l'exemple du World Map au British Museum... Comment l'aborder dans le cadre de ce cours? En faire une analyse tout simplement (les attraits et la faciliter d'utilisation pour les visiteurs/public...)? Expliquer les techniques ou les logiciels utilisés? Ou prendre un exemple d'une plus petite institution?

**Comment by veroforget** [comment]
Bonjour! @emchateau je vous reviens pour l'article sur le thème de collection virtuelle et interactive! Comme l'exemple du World Map au British Museum... Comment l'aborder dans le cadre de ce cours? En faire une analyse tout simplement (les attraits et la facilité d'utilisation pour les visiteurs/public de la page web...)? Expliquer les techniques ou les logiciels utilisés? Ou prendre un exemple d'une plus petite institution?

**Comment by asibella** [comment]
Bonjour à tous ! 
Je n'ai pas trouvé le bon endroit pour passer ce message du coup je le fais ici (sorry!). 
Pour le projet final, j'aimerais travailler sur les dispositifs numériques que les musées peuvent mettre en place. Comme exemple, je peux vous citer la visualisation des données, un application mobile, des audio-guide, des vidéos, une application de visite ludique, des immersions (visuelles, sonores et tactile), des projections, des maquettes interactives...

**Comment by JulienLehoux** [comment]
@asibella je travaille au site historique Marguerite-Bourgeoys dans le Vieux-Montréal et il y a quelques mois, nous avons installés des puces NFC qu'on active avec le téléphone pour recevoir des informations complémentaires sur le bâtiment et les objets de collection. Donc par exemple, si un.e visiteur.se rencontre une des pastilles NFC et qui l'active avec son téléphone, il va tomber sur un lien internet qui donnera un fichier audio sur son environnement (ex. : les vitraux de la chapelle, les tapisseries sur le plafond, etc.) et un petit bloc de textes. Ça remplace essentiellement nos anciens audioguides et à ma connaissance, au moment de l'installation, nous étions le seul musée à Montréal à avoir ce type de technologie. Je fais de la pub pour mon musée, mais tu pourrais faire ton travail là-dessus!

**Comment by asibella** [comment]
@JulienLehoux Whaou c'est un projet vraiment chouette. Si jamais ça tente quelqu'un, ce guide pourrait inciter les musées à développer ce genre de dispositif et ça pourrait être un beau projet final.
