### ISSUE TITLE
Ateliers

### ISSUE THREAD

**Issue by Alissia-CptBath** [ouvroir/museadon#51]
@emchateau pour les ateliers que vous aimeriez organiser hors cours, vous pourriez proposer des dates via un doodle ? https://doodle.com/fr/
Merci

**Comment by emchateau** [comment]
Mieux que ça, je vous propose de renseigner un FramaDate https://framadate.org/gZNYKc5Ku51xGFr2
Merci à tous de bien vouloir renseigner le sondage @ouvroir/museadon 

[Framalibre](https://framalibre.org/) est une association française qui développe des ["chatons numériques"](https://chatons.org/) des services numériques basés sur des logiciels libres comme alternative aux géants du web. Des chatons que vous pouvez reproduire. Au Québec l’association [Facil](https://facil.qc.ca/) développe le même type de projet.
