### ISSUE TITLE
publication article blog question

### ISSUE THREAD

**Issue by Alissia-CptBath** [ouvroir/museadon#54]
@emchateau Bonjour Emmanuel, 
j'ai publiée mon article de blog sur github mais j'ai un petit soucis, je ne parviens pas à le mettre dans _posts.
Pouvez vous m'indiquer ce que j'ai loupée ? ou le déplacer ?
Merci beaucoup !

**Comment by emchateau** [comment]
Chère @Alissia-CptBath, je vais le déplacer. Le fichier avait été créé à la racine du répertoire.
Bien cordialement,
Emmanuel

**Comment by emchateau** [comment]
C’est fait !
