### ISSUE TITLE
Événement en ligne sur les balados en art

### ISSUE THREAD

**Issue by emchateau** [ouvroir/museadon#55]
Un événement en ligne consacré aux baladodiffusions en art a lieu cette semaine, mercredi 17. L’inscription est libre. lhttps://www.eventbrite.co.uk/e/speaking-of-art-art-histories-and-the-podcast-tickets-139632136479

@ouvroir/museadon

**Comment by JulienLehoux** [comment]
Merci de l'avoir partagé ! Je me suis inscris à l'instant.

**Comment by MagalieRouleau** [comment]
Merci @emchateau j'y assisterai aussi!

**Comment by CamilleRV** [comment]
Bonjour, merci pour le partage! 
Est-ce bien à 14h notre heure (18h London)?
