### ISSUE TITLE
Bonjour @emchateau, Est-ce que les enregistrements des conférences du colloque seront accessibles? Je n'ai pas pu assister à la conférence d'Elisabeth Kaine entre autre et j'aurais beaucoup aimé la visionner. Merci

### ISSUE THREAD

**Issue by MagalieRouleau** [ouvroir/museadon#58]

**Comment by CamilleRV** [comment]
@MagalieRouleau tu peux revisionner les conférences sur la page facebook de l'ICOFOM, il y a un facebook live (tu peux reculer ou avancer) 
https://www.facebook.com/icofom

**Comment by emchateau** [comment]
Nous sommes également en train
