### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by veroforget** [ouvroir/museadon#59]
Bonjour à tous! est-ce que quelqu'un pourrait me montrer ou m'expliquer comment mettre une image dans museadon?
J'ai upload mon fichier dans le dossier image et j'ai copier le lien dans mon article de cette manière: ![alt tag](url de ton image). Sans succès malheureusement... :( 
@emchateau @Alissia-CptBath ?

**Comment by Alissia-CptBath** [comment]
@veroforget il faut que tu fasse la commande suivante :  ! [nom de l'image] (liens URL de l'image) . Regarde dans ce liens dans les exemples il y a image : https://guides.github.com/features/mastering-markdown/ ça devrait résoudre ton problème. Essaie et redis moi

**Comment by emchateau** [comment]
Rmq Alissia a ajouté des espaces dans la syntaxe pour que vous puissiez voir les séquences de caractères.
Pour citer du code vous pouvez taper l‘encadrer par des guillemets inverses `
Ou bien utiliser la barre d’outil de l’éditeur dans les réponses des issues comme dans les articles
```
![nom de l'image](liens URL de l'image)
```

**Comment by veroforget** [comment]
C'est bon, j'ai trouvé une autre manière plus facile (vive Youtube haha)!  Merci!

**Comment by veroforget** [comment]
Ben en fait, pour ceux qui veulent savoir j'ai "dragged" mon image dans un issu et j'ai copier le lien par la suite. Donc le markdown ce fait automatiquement et j'ai pu le copier/coller direct après dans mon texte.

**Comment by Alissia-CptBath** [comment]
@veroforget parfait ! Je tag le groupe dans ce cas , ça peut aider @ouvroir/museadon
