### ISSUE TITLE
Déterminer quel est le chat dans la PirateBox

### ISSUE THREAD

**Issue by emchateau** [ouvroir/museadon#61]
@emchateau s’occupe de regarder quel est le chat offert dans la Piratebox
https://piratebox.cc/openwrt:diy

cc @MaeliLC @JuliettePassilly36 @Alissia-CptBath

**Comment by Alissia-CptBath** [comment]
@emchateau avez vous pu voir s'il est possible de configurer le chat de la piratebox ? et comment ce dernier fonctionne ?

**Comment by emchateau** [comment]
J’ai regardé ce n’est pas clair. Visiblement il y a deux modules proposé:
- un chat direct et anonyme 
- un bulletin board
Par ailleurs, on peut installer de manière optionnelle un IRC
Je pense que les deux premiers systèmes ont été développés en propre pour la PirateBox.
