### ISSUE TITLE
Proposer une communication au congrès de la SMQ ?

### ISSUE THREAD

**Issue by emchateau** [ouvroir/museadon#66]
Bonjour, je me demandais ce que vous penseriez de proposer une communication collective au Congrès de la SMQ
https://www.musees.qc.ca/actualites/congres-smq-2021-appel-a-contributions-pour-le-colloque

Le sujet est cette année la Transformation muséale.

@ouvroir/museadon

**Comment by Alissia-CptBath** [comment]
Bonjour, ce serait une super opportunité, mais je ne veux aucunement forcer mon groupe. À titre personnel, je trouve cela intéressant !

**Comment by ArielleAP** [comment]
Je suis partante aussi. Puisque notre équipe a réalisé un projet concret que l'on peut utiliser, j'aimerais beaucoup le faire connaitre et inspirer des musées à se lancer dans le serious game.

**Comment by asibella** [comment]
Merci pour cette proposition. Effectivement, ce serait une très bonne idée.

**Comment by emchateau** [comment]
Lien vers le pad
https://semestriel.framapad.org/p/smq-9n3o?lang=fr

**Comment by JuliettePassilly36** [comment]
Ce serait effectivement une belle opportunité ! Je peux être disponible à partir de début/milieu mai pour commencer à travailler sur le projet !

**Comment by emchateau** [comment]
Bonjour à tous, comme convenu, j'ai déposé une présentation. Vous la trouverez au lien ci-dessus. On croise les doigts. @ouvroir/museadon

**Comment by JuliettePassilly36** [comment]
Bonjour !  Y'a-t-il eu un retour sur la proposition à la SMQ? :)

**Comment by emchateau** [comment]
Bonjour, Pas encore. Je vous tiens au courant.
